import fs from "node:fs";
import vm from "node:vm";

const html=fs.readFileSync("www/index.html","utf8");
const match=html.match(/<script type="application\/json" id="fixture">([\s\S]*?)<\/script>/);
if(!match) throw new Error("fixture script missing");
const fixture=JSON.parse(match[1]);
if(!fixture.dataset_id || !Array.isArray(fixture.experiments) || !Array.isArray(fixture.sources)) throw new Error("invalid PROMETHEUS fixture schema");
if(!fixture.challenge_sources || fixture.challenge_sources.length < 20) throw new Error("challenge source catalog unexpectedly small");
const ids=new Set(fixture.sources.map(s=>s.source_id));
for(const e of fixture.experiments) for(const id of (e.source_ids||[])) if(!ids.has(id)) throw new Error("experiment references unknown source "+id);
const psi98=fixture.experiments.find(e=>e.exp_id==="PSI98-S1");
if(!psi98 || !(psi98.observations||[]).some(o=>o.phenomenon==="burn_duration" && o.measurement?.canonical_value===420)) throw new Error("SAFFIRE S1 burn duration missing");
const data=JSON.parse(fs.readFileSync("data/prometheus_nasa_psi.json","utf8"));
if(data.update_version!=="2026.10.07.3") throw new Error("dataset update version mismatch");

const ai=fs.readFileSync("android/app/src/main/assets/prometheus_ai.js","utf8");
if(!html.includes("window, '__prometheusDataset'")) throw new Error("stable local-AI dataset provider missing");
if(!html.includes("function resetLabFormToBaseline(ds = S.ds)")) throw new Error("virtual-lab recorded-baseline reset helper missing");
if(!html.includes("form: {fuel: '', on: {o2: false, p: false, g: false, t: false, f: false}")) throw new Error("virtual-lab initial constraints should not be stale defaults");
if(!html.includes("Scenario reset to a recorded experiment baseline")) throw new Error("virtual-lab baseline reset action missing");
if(!html.includes("RETRIEVED EVIDENCE · '+numericFinding.level")) throw new Error("virtual-lab evidence chart missing");
if(!html.includes("not a physical combustion simulation")) throw new Error("virtual-lab scientific disclosure missing");
if(!ai.includes("window.__prometheusDataset")) throw new Error("local AI does not consume stable dataset provider");
if(!ai.includes("https://your-domain/v1/agent")) throw new Error("cloud AI endpoint guidance does not match the agent API route");
if(!ai.includes('trace.map(t=>t?.result?.visualization)')) throw new Error("cloud AI tool charts are not rendered in the assistant response");
if(!ai.includes("pending3DResult=rows")) throw new Error("3D evidence visualization ignores the requested scientific variable");
if(!ai.includes("function finiteNumericValue(raw)")) throw new Error("strict chart numeric parser missing");
if(ai.includes("<polyline")) throw new Error("scientific chart must not connect independent experiments with a line");
if(!ai.includes("Categorical experiment values; not a time series")) throw new Error("chart must disclose categorical comparison semantics");
if(!ai.includes("No comparison inferred")) throw new Error("insufficient chart coverage disclosure missing");
const agentServer=fs.readFileSync("agent/server.mjs","utf8");
const agentEvidence=fs.readFileSync("agent/evidence.mjs","utf8");
if(!agentServer.includes('name:"analyze_dataset"') || !agentServer.includes("analyzeDataset(args.operation")) throw new Error("scientific analysis tool is not wired into the LLM agent");
if(!agentEvidence.includes("export function analyzeDataset")) throw new Error("deterministic chart-ready evidence analysis is missing");
if(!fs.existsSync("render.yaml")) throw new Error("cloud agent deployment blueprint missing");
if(!ai.includes("if (loaded && Array.isArray(loaded.experiments)) return loaded;")) throw new Error("local AI dataset bridge validation missing");
if(!ai.includes("#pm-ai-panel{position:fixed!important;inset:28px 0 0 0!important")) throw new Error("AI chat must use a status-bar-safe full-screen viewport layout");
if(!ai.includes("height:calc(100dvh - max(28px,env(safe-area-inset-top,0px)))!important")) throw new Error("AI chat must fill the status-bar-safe dynamic mobile viewport");
if(!ai.includes("top:max(28px,env(safe-area-inset-top,0px))")) throw new Error("AI chat must stay clear of Android status-bar controls");
if(!ai.includes("min-width:48px;min-height:48px")) throw new Error("AI close control must have a reliable touch target");
if(!ai.includes("window.__prometheusBack = function()")) throw new Error("Android Back must close the AI chat before navigating or exiting");
if(!ai.includes("body.pm-ai-fullscreen-open #pm-ai-fab{display:none!important")) throw new Error("floating launcher must hide while full-screen chat is open");
if(!ai.includes("window.__prometheusAIOpen = openAI")) throw new Error("external dashboard action does not open the full-screen chat");
if(!ai.includes('window.addEventListener("pointermove",moveDrag')) throw new Error("movable AI launcher pointer handling missing");
if(!ai.includes('fab.addEventListener("pointerdown"')) throw new Error("AI launcher pointer handling missing");
if(ai.includes("DRAG TO MOVE")) throw new Error("full-screen chat must not show obsolete draggable-panel affordance");
if(ai.includes('panel.querySelector("#pm-ai-head").addEventListener("pointerdown"')) throw new Error("full-screen chat header must not be draggable");
if(html.includes("top:calc(env(safe-area-inset-top,0px) + 8px)!important;bottom:calc(132px")) throw new Error("old full-height mobile AI override still present");

const scripts=[...html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/gi)].map((m,index)=>({attrs:m[1],source:m[2],index}));
scripts.forEach(({attrs,source,index})=>{
  if(/type=["']application\/json["']/i.test(attrs)) return;
  new vm.Script(source,{filename:`www/index.html#script-${index+1}`});
});
console.log("PROMETHEUS web/data validation passed:", fixture.experiments.length, "experiments;", fixture.sources.length, "sources;");

if(!html.includes("function viewDashboard(root)")) throw new Error("interactive AI fire-safety dashboard missing");
if(!html.includes("EVIDENCE COVERAGE RANKING")) throw new Error("dashboard evidence ranking missing");
if(!html.includes("not fire danger")) throw new Error("dashboard must disclose that coverage is not hazard severity");
if(!html.includes("Measured phenomenon")) throw new Error("dashboard phenomenon filter missing");
if(!html.includes("Inspect in Evidence Universe")) throw new Error("dashboard study drill-down missing");
if(!html.includes("Interpret this selection with PROMETHEUS AI")) throw new Error("dashboard-to-agent action missing");
if(!html.includes("ai.ask(question)")) throw new Error("dashboard does not dispatch its current selection to the AI agent");
if(!ai.includes("window.PROMETHEUS_AI = {") || !ai.includes("    ask,")) throw new Error("local evidence agent ask API is not exported");
const mainActivity=fs.readFileSync("android/app/src/main/java/org/crowncouncil/prometheus/MainActivity.java","utf8");
if((mainActivity.match(/postDelayed\(this::injectPrometheusAI/g)||[]).length!==1) throw new Error("AI script should be injected only once per Android startup");
if(mainActivity.includes("window.__prometheusAIStatus='injecting'")) throw new Error("Android injection must not reset the AI singleton guard");
